### PR TITLE
Purpose: Strike "alike"

### PR DESCRIPTION
**Pull request by kemitchell**
@Fishrock123, easiest just to strike?

### CODE REVIEW

**Comment by Fishrock123** [comment]
For posterity, from https://twitter.com/Fishrock123/status/1265443311591948289?s=20

I think this is more clear.

**Comment by kemitchell** [comment]
> I think this is more clear.

By the power vested in me by the Buddy System, I do declare this more clear!

Might I give you a public thanks in THANKS.md?

**Comment by Fishrock123** [comment]
It's just a small thing but if you really want to then sure

**Comment by kemitchell** [comment]
I often find small things are the easiest _not_ to send back. Much appreciated!

**Pull request merged**
