### PR TITLE
Contribute: Clarify license rule

### PR DESCRIPTION
**Pull request by kemitchell**
The hot path here is probably people wanting to use the old academic licenses. We can make that more clear. But also make sure we address _why_ we prefer the modern permissive licenses.

### CODE REVIEW

**Comment by kemitchell** [comment]
This now strikes me as a bad idea. At best, this allows people to continue using the old licenses, despite their flaws. And every accommodation along that line will introduce more uncertainty about the scope of patent licenses.

**Comment by laughinghan** [comment]
I don't totally get it—does Round Robin require excluding MIT licensed code, then?

Discouraging old licenses is good, but pragmatically I like the idea of allowing "legacy-licensed" code, subject to additional conditions/friction (to discourage them still).

**Comment by kemitchell** [comment]
Yes, this should be revisited.

Looking at it again, I think it's best to require a modern permissive license when the contributor has a choice, but allow old and popular licenses---MIT, BSD, Apache---when they're incorporating code released by others without any way to choose new license terms.

**Comment by kemitchell** [comment]
@laughinghan hopefully the new commit I've pushed addresses your concern. I suspect this is worth a new version release.

**Pull request merged**
